# Generated by Django 5.2.6 on 2026-02-21 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(default='No Description')),
                ('file', models.FileField(upload_to='documents/')),
                ('original_filename', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('encryption_key', models.TextField(null=True)),
                ('is_shared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('status', models.IntegerField()),
                ('role', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
