# Generated by Django 5.2.6 on 2026-05-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_signup_storage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharenotes',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
